
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH /  Path("assets_Frame09")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1440x1024")
window.configure(bg = "#ECE7EB")


canvas = Canvas(
    window,
    bg = "#ECE7EB",
    height = 1024,
    width = 1440,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    890.0,
    42.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    580.0,
    42.0,
    image=image_image_2
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_Profile.png"))
button_Profile = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_Profile clicked"),
    relief="flat"
)
button_Profile.place(
    x=1361.184814453125,
    y=17.030452728271484,
    width=44.18265151977539,
    height=44.69343185424805
)

canvas.create_rectangle(
    359.0,
    114.0,
    1419.0,
    268.0,
    fill="#FFFFFF",
    outline="")

button_image_2 = PhotoImage(
    file=relative_to_assets("button_Notification.png"))
button_Notification = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_Notification clicked"),
    relief="flat"
)
button_Notification.place(
    x=1292.0,
    y=17.0,
    width=49.0,
    height=49.0
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    499.0,
    161.0,
    image=image_image_3
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    832.0,
    215.0,
    image=image_image_4
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_Search.png"))
button_Search = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_Search clicked"),
    relief="flat"
)
button_Search.place(
    x=1287.0,
    y=193.0,
    width=102.0,
    height=45.0
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    823.0,
    217.0,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=400.0,
    y=206.0,
    width=846.0,
    height=20.0
)

canvas.create_rectangle(
    359.0,
    298.0,
    1419.0,
    1001.0,
    fill="#FFFFFF",
    outline="")

canvas.create_rectangle(
    389.0,
    429.0,
    1389.0,
    477.0,
    fill="#F7F4F7",
    outline="")

image_image_5 = PhotoImage(
    file=relative_to_assets("image_5.png"))
image_5 = canvas.create_image(
    889.0,
    408.0,
    image=image_image_5
)

canvas.create_text(
    409.0,
    441.0,
    anchor="nw",
    text="C001",
    fill="#374A5A",
    font=("Crimson Pro", 20 * -1)
)

canvas.create_rectangle(
    389.0,
    477.0,
    1389.0,
    525.0,
    fill="#F7F4F7",
    outline="")

canvas.create_text(
    409.0,
    489.0,
    anchor="nw",
    text="C001",
    fill="#374A5A",
    font=("Crimson Pro", 20 * -1)
)

canvas.create_text(
    579.280029296875,
    489.0,
    anchor="nw",
    text="Premium",
    fill="#374A5A",
    font=("Crimson Pro", 20 * -1)
)

canvas.create_text(
    781.0,
    490.0,
    anchor="nw",
    text="20%",
    fill="#374A5A",
    font=("Crimson Pro", 20 * -1)
)

canvas.create_text(
    929.280029296875,
    489.0,
    anchor="nw",
    text="Offer 10% discount on next purchase",
    fill="#374A5A",
    font=("Crimson Pro", 20 * -1)
)

canvas.create_rectangle(
    389.0,
    525.0,
    1389.0,
    573.0,
    fill="#F7F4F7",
    outline="")

canvas.create_text(
    409.0,
    537.0,
    anchor="nw",
    text="C001",
    fill="#374A5A",
    font=("Crimson Pro", 20 * -1)
)

canvas.create_text(
    579.280029296875,
    537.0,
    anchor="nw",
    text="Premium",
    fill="#374A5A",
    font=("Crimson Pro", 20 * -1)
)

canvas.create_text(
    781.0,
    538.0,
    anchor="nw",
    text="20%",
    fill="#374A5A",
    font=("Crimson Pro", 20 * -1)
)

canvas.create_text(
    929.280029296875,
    537.0,
    anchor="nw",
    text="Offer 10% discount on next purchase",
    fill="#374A5A",
    font=("Crimson Pro", 20 * -1)
)

canvas.create_rectangle(
    389.0,
    573.0,
    1389.0,
    621.0,
    fill="#F7F4F7",
    outline="")

canvas.create_text(
    409.0,
    585.0,
    anchor="nw",
    text="C001",
    fill="#374A5A",
    font=("Crimson Pro", 20 * -1)
)

canvas.create_text(
    579.280029296875,
    585.0,
    anchor="nw",
    text="Premium",
    fill="#374A5A",
    font=("Crimson Pro", 20 * -1)
)

canvas.create_text(
    781.0,
    586.0,
    anchor="nw",
    text="20%",
    fill="#374A5A",
    font=("Crimson Pro", 20 * -1)
)

canvas.create_text(
    929.280029296875,
    585.0,
    anchor="nw",
    text="Offer 10% discount on next purchase",
    fill="#374A5A",
    font=("Crimson Pro", 20 * -1)
)

canvas.create_rectangle(
    389.0,
    620.0,
    1389.0,
    668.0,
    fill="#F7F4F7",
    outline="")

canvas.create_text(
    409.0,
    632.0,
    anchor="nw",
    text="C001",
    fill="#374A5A",
    font=("Crimson Pro", 20 * -1)
)

canvas.create_text(
    579.280029296875,
    632.0,
    anchor="nw",
    text="Premium",
    fill="#374A5A",
    font=("Crimson Pro", 20 * -1)
)

canvas.create_text(
    781.0,
    633.0,
    anchor="nw",
    text="20%",
    fill="#374A5A",
    font=("Crimson Pro", 20 * -1)
)

canvas.create_text(
    929.280029296875,
    632.0,
    anchor="nw",
    text="Offer 10% discount on next purchase",
    fill="#374A5A",
    font=("Crimson Pro", 20 * -1)
)

canvas.create_rectangle(
    389.0,
    668.0,
    1389.0,
    716.0,
    fill="#F7F4F7",
    outline="")

canvas.create_text(
    409.0,
    680.0,
    anchor="nw",
    text="C001",
    fill="#374A5A",
    font=("Crimson Pro", 20 * -1)
)

canvas.create_text(
    579.280029296875,
    680.0,
    anchor="nw",
    text="Premium",
    fill="#374A5A",
    font=("Crimson Pro", 20 * -1)
)

canvas.create_text(
    781.0,
    681.0,
    anchor="nw",
    text="20%",
    fill="#374A5A",
    font=("Crimson Pro", 20 * -1)
)

canvas.create_text(
    929.280029296875,
    680.0,
    anchor="nw",
    text="Offer 10% discount on next purchase",
    fill="#374A5A",
    font=("Crimson Pro", 20 * -1)
)

canvas.create_rectangle(
    389.0,
    716.0,
    1389.0,
    764.0,
    fill="#F7F4F7",
    outline="")

canvas.create_text(
    409.0,
    728.0,
    anchor="nw",
    text="C001",
    fill="#374A5A",
    font=("Crimson Pro", 20 * -1)
)

canvas.create_text(
    579.280029296875,
    728.0,
    anchor="nw",
    text="Premium",
    fill="#374A5A",
    font=("Crimson Pro", 20 * -1)
)

canvas.create_text(
    781.0,
    729.0,
    anchor="nw",
    text="20%",
    fill="#374A5A",
    font=("Crimson Pro", 20 * -1)
)

canvas.create_text(
    929.280029296875,
    728.0,
    anchor="nw",
    text="Offer 10% discount on next purchase",
    fill="#374A5A",
    font=("Crimson Pro", 20 * -1)
)

canvas.create_rectangle(
    389.0,
    764.0,
    1389.0,
    812.0,
    fill="#F7F4F7",
    outline="")

canvas.create_text(
    409.0,
    776.0,
    anchor="nw",
    text="C001",
    fill="#374A5A",
    font=("Crimson Pro", 20 * -1)
)

canvas.create_text(
    579.280029296875,
    776.0,
    anchor="nw",
    text="Premium",
    fill="#374A5A",
    font=("Crimson Pro", 20 * -1)
)

canvas.create_text(
    781.0,
    777.0,
    anchor="nw",
    text="20%",
    fill="#374A5A",
    font=("Crimson Pro", 20 * -1)
)

canvas.create_text(
    929.280029296875,
    776.0,
    anchor="nw",
    text="Offer 10% discount on next purchase",
    fill="#374A5A",
    font=("Crimson Pro", 20 * -1)
)

canvas.create_rectangle(
    389.0,
    812.0,
    1389.0,
    860.0,
    fill="#F7F4F7",
    outline="")

canvas.create_text(
    409.0,
    824.0,
    anchor="nw",
    text="C001",
    fill="#374A5A",
    font=("Crimson Pro", 20 * -1)
)

canvas.create_text(
    579.280029296875,
    824.0,
    anchor="nw",
    text="Premium",
    fill="#374A5A",
    font=("Crimson Pro", 20 * -1)
)

canvas.create_text(
    781.0,
    825.0,
    anchor="nw",
    text="20%",
    fill="#374A5A",
    font=("Crimson Pro", 20 * -1)
)

canvas.create_text(
    929.280029296875,
    824.0,
    anchor="nw",
    text="Offer 10% discount on next purchase",
    fill="#374A5A",
    font=("Crimson Pro", 20 * -1)
)

canvas.create_rectangle(
    389.0,
    860.0,
    1389.0,
    908.0,
    fill="#F7F4F7",
    outline="")

canvas.create_text(
    409.0,
    872.0,
    anchor="nw",
    text="C001",
    fill="#374A5A",
    font=("Crimson Pro", 20 * -1)
)

canvas.create_text(
    579.280029296875,
    872.0,
    anchor="nw",
    text="Premium",
    fill="#374A5A",
    font=("Crimson Pro", 20 * -1)
)

canvas.create_text(
    781.0,
    873.0,
    anchor="nw",
    text="20%",
    fill="#374A5A",
    font=("Crimson Pro", 20 * -1)
)

canvas.create_text(
    929.280029296875,
    872.0,
    anchor="nw",
    text="Offer 10% discount on next purchase",
    fill="#374A5A",
    font=("Crimson Pro", 20 * -1)
)

canvas.create_text(
    579.280029296875,
    441.0,
    anchor="nw",
    text="Premium",
    fill="#374A5A",
    font=("Crimson Pro", 20 * -1)
)

canvas.create_text(
    781.0,
    442.0,
    anchor="nw",
    text="20%",
    fill="#374A5A",
    font=("Crimson Pro", 20 * -1)
)

canvas.create_text(
    929.280029296875,
    441.0,
    anchor="nw",
    text="Offer 10% discount on next purchase",
    fill="#374A5A",
    font=("Crimson Pro", 20 * -1)
)

image_image_6 = PhotoImage(
    file=relative_to_assets("image_6.png"))
image_6 = canvas.create_image(
    529.0,
    345.0,
    image=image_image_6
)

canvas.create_text(
    121.0,
    918.0,
    anchor="nw",
    text="ChuLiBi",
    fill="#FDE5F4",
    font=("RubikBurned Regular", 35 * -1)
)

image_image_7 = PhotoImage(
    file=relative_to_assets("image_7.png"))
image_7 = canvas.create_image(
    170.0,
    512.0,
    image=image_image_7
)

canvas.create_text(
    99.0,
    927.0,
    anchor="nw",
    text="ChuLiBi",
    fill="#FDE5F4",
    font=("RubikBurned Regular", 35 * -1)
)

image_image_8 = PhotoImage(
    file=relative_to_assets("image_8.png"))
image_8 = canvas.create_image(
    163.0,
    101.0,
    image=image_image_8
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_Customer_Analysis.png"))
button_Customer_Analysis = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_Customer_Analysis clicked"),
    relief="flat"
)
button_Customer_Analysis.place(
    x=1.0,
    y=302.0,
    width=337.0,
    height=77.0
)

button_image_5 = PhotoImage(
    file=relative_to_assets("button_Churn.png"))
button_Churn = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_Churn clicked"),
    relief="flat"
)
button_Churn.place(
    x=1.0,
    y=381.0,
    width=337.0,
    height=86.0
)

button_image_6 = PhotoImage(
    file=relative_to_assets("button_Delivery.png"))
button_Delivery = Button(
    image=button_image_6,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_Delivery clicked"),
    relief="flat"
)
button_Delivery.place(
    x=1.0,
    y=552.0,
    width=337.0,
    height=90.0
)

button_image_7 = PhotoImage(
    file=relative_to_assets("button_Report.png"))
button_Report = Button(
    image=button_image_7,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_Report clicked"),
    relief="flat"
)
button_Report.place(
    x=0.0,
    y=646.0,
    width=340.0,
    height=88.0
)

button_image_8 = PhotoImage(
    file=relative_to_assets("button_Recommendation.png"))
button_Recommendation = Button(
    image=button_image_8,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_Recommendation clicked"),
    relief="flat"
)
button_Recommendation.place(
    x=0.0,
    y=467.0,
    width=340.0,
    height=84.0
)

button_image_9 = PhotoImage(
    file=relative_to_assets("button_Dashboard.png"))
button_Dashboard = Button(
    image=button_image_9,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_Dashboard clicked"),
    relief="flat"
)
button_Dashboard.place(
    x=1.0,
    y=228.0,
    width=339.0,
    height=56.0
)
window.resizable(False, False)
window.mainloop()
