
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("assets_Frame04")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1440x1024")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 1024,
    width = 1440,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    360.0,
    512.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    360.0,
    512.0,
    image=image_image_2
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    1079.0,
    512.0,
    image=image_image_3
)

canvas.create_text(
    918.0,
    681.0,
    anchor="nw",
    text="Already have an account ?",
    fill="#000000",
    font=("Crimson Pro SemiBold", 23 * -1)
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    720.0,
    512.0,
    image=image_image_4
)

canvas.create_text(
    837.0,
    293.0,
    anchor="nw",
    text="Forget Password",
    fill="#000000",
    font=("Young Serif", 55 * -1)
)

image_image_5 = PhotoImage(
    file=relative_to_assets("image_5.png"))
image_5 = canvas.create_image(
    357.0,
    351.0,
    image=image_image_5
)

canvas.create_text(
    277.0,
    885.0,
    anchor="nw",
    text="ChuLiBi",
    fill="#FDE5F4",
    font=("Rubik Burned", 35 * -1)
)

canvas.create_text(
    60.0,
    637.0,
    anchor="nw",
    text="we’ll send you a verification code",
    fill="#FFFFFF",
    font=("Crimson Pro SemiBold", 40 * -1)
)

canvas.create_text(
    202.0,
    586.0,
    anchor="nw",
    text="Enter your email ",
    fill="#FFFFFF",
    font=("Crimson Pro SemiBold", 40 * -1)
)

canvas.create_text(
    910.0,
    428.0,
    anchor="nw",
    text="Email",
    fill="#000000",
    font=("Crimson Pro SemiBold", 28 * -1)
)

entry_image_email = PhotoImage(
    file=relative_to_assets("entry_email.png"))
entry_bg_1 = canvas.create_image(
    1081.5,
    492.0,
    image=entry_image_email
)
entry_email = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0,
    font=("Crimson Pro Regular", 26 * -1)
)
entry_email.place(
    x=857.0,
    y=462.0,
    width=449.0,
    height=58.0
)

image_image_6 = PhotoImage(
    file=relative_to_assets("image_6.png"))
image_6 = canvas.create_image(
    882.0,
    441.0,
    image=image_image_6
)

image_image_7 = PhotoImage(
    file=relative_to_assets("image_7.png"))
image_7 = canvas.create_image(
    882.0,
    444.0,
    image=image_image_7
)

button_image_sendOTP = PhotoImage(
    file=relative_to_assets("button_sendOTP.png"))
button_sendOTP = Button(
    image=button_image_sendOTP,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_send otp clicked"),
    relief="flat"
)
button_sendOTP.place(
    x=842.0,
    y=574.0,
    width=479.0,
    height=70.0
)

canvas.create_text(
    76.0,
    476.0,
    anchor="nw",
    text="Oops, it happens!",
    fill="#FFFFFF",
    font=("Young Serif", 65 * -1)
)

button_image_login = PhotoImage(
    file=relative_to_assets("button_login.png"))
button_login = Button(
    image=button_image_login,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("Clicked login button"),
    relief="flat"
)
button_login.place(
    x=1176.0,
    y=681.0,
    width=63.0,
    height=24.0
)
window.resizable(False, False)
window.mainloop()
