
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path


from tkinter import Tk, Canvas, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("480x329")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 329,
    width = 480,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_text(
    50.0,
    165.0,
    anchor="nw",
    text="Invalid username or password",
    fill="#706093",
    font=("Young Serif", 24 * -1)
)

canvas.create_text(
    93.0,
    204.0,
    anchor="nw",
    text="Please enter correct username or password! ",
    fill="#B992B9",
    font=("Crimson Pro Regular", 17 * -1)
)

image_image_1 = PhotoImage(
    file=relative_to_assets("image_cancel.png"))
image_1 = canvas.create_image(
    240.0,
    97.0,
    image=image_image_1
)

button_image_okay = PhotoImage(
    file=relative_to_assets("button_okay.png"))
button_1 = Button(
    image=button_image_okay,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_okay clicked"),
    relief="flat"
)
button_1.place(
    x=95.0,
    y=242.0,
    width=289.0,
    height=61.0
)
window.resizable(False, False)
window.mainloop()
