
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("assets_Frame02")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1440x1024")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 1024,
    width = 1440,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    360.0,
    512.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    360.0,
    512.0,
    image=image_image_2
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    1081.0,
    513.0,
    image=image_image_3
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    720.0,
    512.0,
    image=image_image_4
)

canvas.create_text(
    915.0,
    928.0,
    anchor="nw",
    text="Already have an account ?",
    fill="#000000",
    font=("Crimson Pro SemiBold", 23 * -1)
)

canvas.create_text(
    915.0,
    813.0,
    anchor="nw",
    text="I agree to Terms & Privacy Policy",
    fill="#000000",
    font=("Crimson Pro SemiBold", 23 * -1)
)

canvas.create_text(
    874.0,
    117.0,
    anchor="nw",
    text="Create Account",
    fill="#000000",
    font=("Young Serif", 55 * -1)
)

image_image_5 = PhotoImage(
    file=relative_to_assets("image_5.png"))
image_5 = canvas.create_image(
    360.0,
    340.0,
    image=image_image_5
)

canvas.create_text(
    906.0,
    539.0,
    anchor="nw",
    text="Password",
    fill="#000000",
    font=("Crimson Pro SemiBold", 28 * -1)
)

entry_image_password = PhotoImage(
    file=relative_to_assets("entry_password.png"))
entry_bg_1 = canvas.create_image(
    1083.5,
    609.5,
    image=entry_image_password
)
entry_password = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0,
    font=("Crimson Pro Regular", 26 * -1)
)
entry_password.place(
    x=859.0,
    y=575.0,
    width=449.0,
    height=67.0
)

image_image_6 = PhotoImage(
    file=relative_to_assets("image_6.png"))
image_6 = canvas.create_image(
    877.0,
    556.0,
    image=image_image_6
)

image_image_7 = PhotoImage(
    file=relative_to_assets("image_7.png"))
image_7 = canvas.create_image(
    876.0,
    694.0,
    image=image_image_7
)

image_image_8 = PhotoImage(
    file=relative_to_assets("image_8.png"))
image_8 = canvas.create_image(
    878.0,
    543.0,
    image=image_image_8
)

image_image_9 = PhotoImage(
    file=relative_to_assets("image_9.png"))
image_9 = canvas.create_image(
    877.0,
    681.0,
    image=image_image_9
)

canvas.create_text(
    900.0,
    680.0,
    anchor="nw",
    text="Confirm password",
    fill="#000000",
    font=("Crimson Pro SemiBold", 28 * -1)
)

entry_image_password_confirm = PhotoImage(
    file=relative_to_assets("entry_password_confirm.png"))
entry_bg_2 = canvas.create_image(
    1083.5,
    748.5,
    image=entry_image_password_confirm
)
entry_password_confirm = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0,
    font=("Crimson Pro Regular", 26 * -1)
)
entry_password_confirm.place(
    x=859.0,
    y=714.0,
    width=449.0,
    height=67.0
)

canvas.create_text(
    49.0,
    31.0,
    anchor="nw",
    text="ChuLiBi",
    fill="#FDE5F4",
    font=("Rubik Burned Regular", 35 * -1)
)

# Load image cho button register
button_register_img = PhotoImage(file=relative_to_assets("button_Register.png"))

# Tạo button register
button_register = Button(
    image=button_register_img,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("Register button clicked"),
    relief="flat"
)
# Giữ reference ảnh để không bị GC
button_register.image = button_register_img

# Đặt vị trí
button_register.place(
    x=839.0,
    y=848.0,
    width=473.0,
    height=68.0
)
canvas.create_text(
    76.0,
    476.0,
    anchor="nw",
    text="Join ChuLiBi today",
    fill="#FFFFFF",
    font=("Young Serif", 60 * -1)
)

canvas.create_text(
    139.0,
    587.0,
    anchor="nw",
    text="Let’s start building AI",
    fill="#FFFFFF",
    font=("Crimson Pro SemiBold", 40 * -1)
)

canvas.create_text(
    139.0,
    645.0,
    anchor="nw",
    text="powered insights together",
    fill="#FFFFFF",
    font=("Crimson Pro SemiBold", 40 * -1)
)

canvas.create_text(
    903.0,
    271.0,
    anchor="nw",
    text="Username",
    fill="#000000",
    font=("Crimson Pro SemiBold", 28 * -1)
)

entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_username.png"))
entry_bg_3 = canvas.create_image(
    1083.5,
    338.5,
    image=entry_image_3
)
entry_username = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0,
    font=("Crimson Pro Regular", 26 * -1)
)
entry_username.place(
    x=859.0,
    y=304.0,
    width=449.0,
    height=67.0
)

image_image_10 = PhotoImage(
    file=relative_to_assets("image_10.png"))
image_10 = canvas.create_image(
    875.0,
    287.0,
    image=image_image_10
)

image_image_11 = PhotoImage(
    file=relative_to_assets("image_11.png"))
image_11 = canvas.create_image(
    875.0,
    270.0,
    image=image_image_11
)

canvas.create_text(
    904.0,
    401.0,
    anchor="nw",
    text="Email",
    fill="#000000",
    font=("Crimson Pro SemiBold", 28 * -1)
)

entry_image_email = PhotoImage(
    file=relative_to_assets("entry_email.png"))
entry_bg_4 = canvas.create_image(
    1083.5,
    472.5,
    image=entry_image_email
)
entry_email = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    font=("Crimson Pro Regular", 26 * -1),
    highlightthickness=0
)
entry_email.place(
    x=859.0,
    y=438.0,
    width=449.0,
    height=67.0
)

image_image_12 = PhotoImage(
    file=relative_to_assets("image_12.png"))
image_12 = canvas.create_image(
    876.0,
    414.0,
    image=image_image_12
)

image_image_13 = PhotoImage(
    file=relative_to_assets("image_13.png"))
image_13 = canvas.create_image(
    876.0,
    417.0,
    image=image_image_13
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=887.0,
    y=810.0,
    width=21.5,
    height=23.0
)

# Load image cho button eyes
button_eyes_img = PhotoImage(file=relative_to_assets("button_eyes_1.png"))

# Tạo button eyes
button_eyes_1 = Button(
    image=button_eyes_img,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("Eyes button clicked"),
    relief="flat"
)

# Giữ reference ảnh để không bị GC
button_eyes_1.image = button_eyes_img

# Đặt vị trí
button_eyes_1.place(
    x=1270.0,
    y=597.0,
    width=30.0,
    height=21.0
)
# Load image cho button eyes 2
button_eyes_2_img = PhotoImage(file=relative_to_assets("button_eyes_2.png"))

# Tạo button
button_eyes_2 = Button(
    image=button_eyes_2_img,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("Eyes 2 button clicked"),
    relief="flat"
)

# Giữ reference ảnh để không bị GC
button_eyes_2.image = button_eyes_2_img

# Đặt vị trí
button_eyes_2.place(
    x=1270.0,
    y=738.0,
    width=30.0,
    height=21.0
)

# Load image cho button login nhỏ
button_login_img = PhotoImage(file=relative_to_assets("button_login.png"))

# Tạo button
button_login = Button(
    image=button_login_img,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("Login button clicked"),
    relief="flat"
)

# Giữ reference ảnh để không bị GC
button_login.image = button_login_img

# Đặt vị trí
button_login.place(
    x=1170.0,
    y=933.0,
    width=70.0,
    height=22.0
)

window.resizable(False, False)
window.mainloop()
