
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("assets_Frame01")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1440x1024")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 1024,
    width = 1440,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    360.0,
    512.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    1073.0,
    631.0,
    image=image_image_2
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    720.0,
    512.0,
    image=image_image_3
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    359.0,
    512.0,
    image=image_image_4
)

canvas.create_text(
    921.0,
    851.0,
    anchor="nw",
    text="Don’t have an account?  ",
    fill="#000000",
    font=("Crimson Pro SemiBold", 23 * -1)
)

canvas.create_text(
    957.0,
    792.0,
    anchor="nw",
    text="Or",
    fill="#000000",
    font=("Crimson Pro SemiBold", 23 * -1)
)

canvas.create_text(
    883.0,
    456.0,
    anchor="nw",
    text="Username",
    fill="#000000",
    font=("Crimson Pro SemiBold", 28 * -1)
)

canvas.create_text(
    969.0,
    345.0,
    anchor="nw",
    text="Login ",
    fill="#000000",
    font=("Young Serif", 64 * -1)
)

canvas.create_text(
    883.0,
    570.0,
    anchor="nw",
    text="Password",
    fill="#000000",
    font=("Crimson Pro SemiBold", 28 * -1)
)

# Username Entry
entry_username_img = PhotoImage(file=relative_to_assets("entry_username.png"))
entry_bg_1 = canvas.create_image(
    1065.0,
    524.0,
    image=entry_username_img
)

entry_username = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0,
    font=("Crimson Pro Regular", 26 * -1),
    show="*"
)
entry_username.place(
    x=855.0,
    y=494.0,
    width=420.0,
    height=58.0
)

# Giữ reference ảnh
entry_username.image = entry_username_img


# Password Entry
entry_password_img = PhotoImage(file=relative_to_assets("entry_password.png"))
entry_bg_2 = canvas.create_image(
    1065.0,
    644.0,
    image=entry_password_img
)

entry_password = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0,
    font=("Crimson Pro Regular", 26 * -1),
    show ="*"
)
entry_password.place(
    x=855.0,
    y=614.0,
    width=420.0,
    height=58.0
)

# Giữ reference ảnh
entry_password.image = entry_password_img

image_image_5 = PhotoImage(
    file=relative_to_assets("image_5.png"))
image_5 = canvas.create_image(
    1061.0,
    144.0,
    image=image_image_5
)

canvas.create_text(
    80.0,
    347.0,
    anchor="nw",
    text="Welcome back to ",
    fill="#FFFFFF",
    font=("Young Serif", 65 * -1)
)

canvas.create_text(
    206.0,
    454.0,
    anchor="nw",
    text="ChuLiBi ",
    fill="#FFFFFF",
    font=("Young Serif", 70 * -1)
)

canvas.create_text(
    33.0,
    595.0,
    anchor="nw",
    text="Your AI data buddy for smarter insights",
    fill="#FFFFFF",
    font=("Crimson Pro SemiBold", 40 * -1)
)

image_image_6 = PhotoImage(
    file=relative_to_assets("image_6.png"))
image_6 = canvas.create_image(
    863.0,
    471.0,
    image=image_image_6
)

image_image_7 = PhotoImage(
    file=relative_to_assets("image_7.png"))
image_7 = canvas.create_image(
    863.0,
    482.0,
    image=image_image_7
)

image_image_8 = PhotoImage(
    file=relative_to_assets("image_8.png"))
image_8 = canvas.create_image(
    864.0,
    595.0,
    image=image_image_8
)

image_image_9 = PhotoImage(
    file=relative_to_assets("image_9.png"))
image_9 = canvas.create_image(
    864.0,
    586.0,
    image=image_image_9
)

image_image_10 = PhotoImage(
    file=relative_to_assets("image_10.png"))
image_10 = canvas.create_image(
    867.0,
    595.0,
    image=image_image_10
)

image_image_11 = PhotoImage(
    file=relative_to_assets("image_11.png"))
image_11 = canvas.create_image(
    864.010009765625,
    595.0,
    image=image_image_11
)

image_image_12 = PhotoImage(
    file=relative_to_assets("image_12.png"))
image_12 = canvas.create_image(
    861.02001953125,
    595.0,
    image=image_image_12
)

canvas.create_text(
    49.0,
    31.0,
    anchor="nw",
    text="ChuLiBi",
    fill="#FDE5F4",
    font=("Rubik Burned Regular", 35 * -1)
)
# Button_eyes
# Load image
eyes_img = PhotoImage(file=relative_to_assets("button_eyes.png"))

# Tạo button với image
button_eyes = Button(
    image=eyes_img,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("Eyes button clicked"),
    relief="flat"
)

button_eyes.image = eyes_img  # giữ reference để không bị GC
button_eyes.place(
    x=1243.0,
    y=635.0,
    width=30.0,
    height=21.0
)
# Button_register
# Load image
register_img = PhotoImage(file=relative_to_assets("button_register.png"))
# Tạo button với image
button_register = Button(
    image=register_img,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("Register button clicked"),
    relief="flat"
)
button_register.image = register_img  # giữ reference để ảnh không bị GC
button_register.place(
    x=1151.0,
    y=855.0,
    width=92.0,
    height=24.0
)
# Button forget password
# Load image
forget_img = PhotoImage(file=relative_to_assets("button_forget_password.png"))

# Tạo button với image
button_forget_password = Button(
    image=forget_img,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("Forget Password clicked"),
    relief="flat"
)

# Giữ reference để ảnh không bị GC
button_forget_password.image = forget_img

button_forget_password.place(
    x=1149.0,
    y=680.0,
    width=141.0,
    height=20.0
)
# Button Login
# Load image
login_img = PhotoImage(file=relative_to_assets("button_login.png"))

# Tạo button với image
button_login = Button(
    image=login_img,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("Login button clicked"),
    relief="flat"
)

# Giữ reference để ảnh không bị GC
button_login.image = login_img

button_login.place(
    x=848.0,
    y=714.0,
    width=450.0,
    height=61.0
)

image_image_13 = PhotoImage(
    file=relative_to_assets("image_13.png"))
image_13 = canvas.create_image(
    1020.0,
    810.0,
    image=image_image_13
)

image_image_14 = PhotoImage(
    file=relative_to_assets("image_14.png"))
image_14 = canvas.create_image(
    1100.0,
    810.0,
    image=image_image_14
)
window.resizable(False, False)
window.mainloop()
