# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer

from pathlib import Path
from tkinter import Tk, Canvas, Entry, Button, PhotoImage, Frame
from ui_content_Frame10 import build_table  # <-- bảng có scrollbar

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("assets_Frame10")

def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

window = Tk()
window.geometry("1440x1024")
window.configure(bg="#ECE7EB")

canvas = Canvas(
    window, bg="#ECE7EB", height=1024, width=1440,
    bd=0, highlightthickness=0, relief="ridge"
)
canvas.place(x=0, y=0)

# ---- top bar ----
image_image_1 = PhotoImage(file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(890.0, 42.0, image=image_image_1)

canvas.create_text(
    385.0, 14.0, anchor="nw",
    text="Recommendations",
    fill="#000000", font=("Young Serif", 40 * -1),
)

button_image_1 = PhotoImage(file=relative_to_assets("button_Profile.png"))
button_Profile = Button(
    image=button_image_1, borderwidth=0, highlightthickness=0,
    command=lambda: print("button_Profile clicked"), relief="flat",
)
button_Profile.place(x=1361.18, y=17.03, width=44.18, height=44.69)

button_image_2 = PhotoImage(file=relative_to_assets("button_Noti.png"))
button_Noti = Button(
    image=button_image_2, borderwidth=0, highlightthickness=0,
    command=lambda: print("button_Noti clicked"), relief="flat",
)
button_Noti.place(x=1292.0, y=17.0, width=49.0, height=49.0)

# ---- search block ----
canvas.create_text(
    389.0, 144.0, anchor="nw",
    text="Customer research",
    fill="#374A5A", font=("Young Serif", 24 * -1),
)

image_image_2 = PhotoImage(file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(832.0, 215.0, image=image_image_2)

button_image_3 = PhotoImage(file=relative_to_assets("button_Search.png"))
button_Search = Button(
    image=button_image_3, borderwidth=0, highlightthickness=0,
    command=lambda: print("button_Search clicked"), relief="flat",
)
button_Search.place(x=1287.0, y=193.0, width=102.0, height=45.0)

entry_image_1 = PhotoImage(file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(823.0, 217.0, image=entry_image_1)
entry_1 = Entry(bd=0, bg="#FFFFFF", fg="#000716", highlightthickness=0)
entry_1.place(x=400.0, y=206.0, width=846.0, height=20.0)

# ---- card trắng chứa bảng ----
canvas.create_rectangle(359.0, 298.0, 1419.0, 1001.0, fill="#FFFFFF", outline="")
canvas.create_text(
    389.0, 328.0, anchor="nw",
    text="Recommendations Table",
    fill="#374A5A", font=("Young Serif", 24 * -1),
)

# ==== TABLE WITH SCROLLBAR (only inside card) ====
# Kích thước/tọa độ vùng bảng bên trong card
TABLE_X = 389      # mép trái vùng hiển thị bảng
TABLE_Y = 366      # dưới tiêu đề một chút
TABLE_W = 1389 - 389
TABLE_H = 1001 - 366

table_holder = Frame(window, bg="#FFFFFF")
table_holder.place(x=TABLE_X, y=TABLE_Y, width=TABLE_W, height=TABLE_H)

table_canvas = build_table(table_holder, TABLE_W, TABLE_H)
table_canvas.pack(fill="both", expand=True)

# ---- sidebar & mascot giữ nguyên, vẫn đậm nét ----
canvas.create_text(99.0, 927.0, anchor="nw",
                   text="ChuLiBi", fill="#FDE5F4",
                   font=("Rubik Burned Regular", 35 * -1))

image_image_4 = PhotoImage(file=relative_to_assets("image_4.png"))  # sidebar gradient + ong
image_4 = canvas.create_image(170.0, 512.0, image=image_image_4)

image_image_5 = PhotoImage(file=relative_to_assets("image_5.png"))  # ong & logo trên sidebar
image_5 = canvas.create_image(163.0, 101.0, image=image_image_5)

# ---- sidebar buttons giữ nguyên ----
btn_assets = {
    "button_Customer.png": (1.0, 302.0, 337.0, 77.0),
    "button_Churn.png": (1.0, 381.0, 337.0, 86.0),
    "button_Delivery.png": (1.0, 552.0, 337.0, 90.0),
    "button_Report.png": (0.0, 646.0, 340.0, 88.0),
    "button_Recommend.png": (0.0, 467.0, 340.0, 84.0),
    "button_Dashboard.png": (1.0, 228.0, 339.0, 56.0),
}
for fname, (x, y, w, h) in btn_assets.items():
    img = PhotoImage(file=relative_to_assets(fname))
    btn = Button(image=img, borderwidth=0, highlightthickness=0,
                 command=lambda n=fname: print(n, "clicked"), relief="flat")
    btn.image = img
    btn.place(x=x, y=y, width=w, height=h)

window.resizable(False, False)
window.mainloop()
