
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH /  Path("assets_Frame10")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1440x1024")
window.configure(bg = "#ECE7EB")


canvas = Canvas(
    window,
    bg = "#ECE7EB",
    height = 1024,
    width = 1440,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    890.0,
    42.0,
    image=image_image_1
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_Profile.png"))
button_Profile = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_Profile clicked"),
    relief="flat"
)
button_Profile.place(
    x=1361.184814453125,
    y=17.03045654296875,
    width=44.18265151977539,
    height=44.69343185424805
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_Notification.png"))
button_Notification = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_Notification clicked"),
    relief="flat"
)
button_Notification.place(
    x=1292.0,
    y=17.0,
    width=49.0,
    height=49.0
)

canvas.create_text(
    121.0,
    918.0,
    anchor="nw",
    text="ChuLiBi",
    fill="#FDE5F4",
    font=("RubikBurned Regular", 35 * -1)
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    170.0,
    512.0,
    image=image_image_2
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_Dashboard.png"))
button_Dashboard = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_Dashboard clicked"),
    relief="flat"
)
button_Dashboard.place(
    x=1.0,
    y=228.0,
    width=339.0,
    height=56.0
)

canvas.create_text(
    99.0,
    927.0,
    anchor="nw",
    text="ChuLiBi",
    fill="#FDE5F4",
    font=("RubikBurned Regular", 35 * -1)
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    163.0,
    101.0,
    image=image_image_3
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_Customer_Analysis.png"))
button_Customer_Analysis = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_Customer_Analysis clicked"),
    relief="flat"
)
button_Customer_Analysis.place(
    x=1.0,
    y=302.0,
    width=337.0,
    height=77.0
)

button_image_5 = PhotoImage(
    file=relative_to_assets("button_Churn.png"))
button_Churn = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_Churn clicked"),
    relief="flat"
)
button_Churn.place(
    x=1.0,
    y=381.0,
    width=337.0,
    height=86.0
)

button_image_6 = PhotoImage(
    file=relative_to_assets("button_Report.png"))
button_Report = Button(
    image=button_image_6,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_Report clicked"),
    relief="flat"
)
button_Report.place(
    x=0.0,
    y=646.0,
    width=340.0,
    height=88.0
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    525.5,
    223.0,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=400.0,
    y=212.0,
    width=251.0,
    height=20.0
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    885.0,
    223.0,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=761.0,
    y=212.0,
    width=248.0,
    height=20.0
)

entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_3.png"))
entry_bg_3 = canvas.create_image(
    1249.5,
    223.0,
    image=entry_image_3
)
entry_3 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_3.place(
    x=1123.0,
    y=212.0,
    width=253.0,
    height=20.0
)

entry_image_4 = PhotoImage(
    file=relative_to_assets("entry_4.png"))
entry_bg_4 = canvas.create_image(
    529.5,
    305.0,
    image=entry_image_4
)
entry_4 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_4.place(
    x=404.0,
    y=294.0,
    width=251.0,
    height=20.0
)

entry_image_5 = PhotoImage(
    file=relative_to_assets("entry_5.png"))
entry_bg_5 = canvas.create_image(
    885.0,
    304.0,
    image=entry_image_5
)
entry_5 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_5.place(
    x=761.0,
    y=293.0,
    width=248.0,
    height=20.0
)

button_image_7 = PhotoImage(
    file=relative_to_assets("button_Recommendation.png"))
button_Recommendation = Button(
    image=button_image_7,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_Recommendation clicked"),
    relief="flat"
)
button_Recommendation.place(
    x=0.0,
    y=469.0,
    width=336.0,
    height=82.0
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    890.0,
    347.0,
    image=image_image_4
)

button_image_8 = PhotoImage(
    file=relative_to_assets("button_Predict.png"))
button_Predict = Button(
    image=button_image_8,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_Predict clicked"),
    relief="flat"
)
button_Predict.place(
    x=390.0,
    y=347.0,
    width=112.0,
    height=38.0
)

canvas.create_text(
    408.0,
    467.0,
    anchor="nw",
    text="85%",
    fill="#FF8C69",
    font=("Crimson Pro", 40 * -1)
)

canvas.create_text(
    410.0,
    528.0,
    anchor="nw",
    text="High risk of late delivery",
    fill="#6B6B7A",
    font=("Crimson Pro", 18 * -1)
)

canvas.create_text(
    915.0,
    470.0,
    anchor="nw",
    text="Prioritize this order in kitchen queue",
    fill="#374A5A",
    font=("Crimson Pro", 18 * -1)
)

canvas.create_text(
    915.0,
    496.0,
    anchor="nw",
    text="Assign experienced delivery partner",
    fill="#374A5A",
    font=("Crimson Pro", 18 * -1)
)

canvas.create_text(
    915.0,
    521.0,
    anchor="nw",
    text="Send proactive notification to customer",
    fill="#374A5A",
    font=("Crimson Pro", 18 * -1)
)

image_image_5 = PhotoImage(
    file=relative_to_assets("image_5.png"))
image_5 = canvas.create_image(
    890.0,
    814.0,
    image=image_image_5
)

image_image_6 = PhotoImage(
    file=relative_to_assets("image_6.png"))
image_6 = canvas.create_image(
    890.0,
    746.0,
    image=image_image_6
)

image_image_7 = PhotoImage(
    file=relative_to_assets("image_7.png"))
image_7 = canvas.create_image(
    890.0,
    788.0,
    image=image_image_7
)

canvas.create_text(
    1075.0,
    778.0,
    anchor="nw",
    text="Premium",
    fill="#374A5A",
    font=("Crimson Pro", 20 * -1)
)

canvas.create_text(
    408.0,
    778.0,
    anchor="nw",
    text="C001",
    fill="#374A5A",
    font=("Crimson Pro", 20 * -1)
)

canvas.create_text(
    741.0,
    777.0,
    anchor="nw",
    text="85%",
    fill="#374A5A",
    font=("Crimson Pro", 20 * -1)
)

image_image_8 = PhotoImage(
    file=relative_to_assets("image_8.png"))
image_8 = canvas.create_image(
    890.0,
    788.0,
    image=image_image_8
)

canvas.create_text(
    1075.0,
    778.0,
    anchor="nw",
    text="Premium",
    fill="#374A5A",
    font=("Crimson Pro", 20 * -1)
)

canvas.create_text(
    408.0,
    778.0,
    anchor="nw",
    text="C001",
    fill="#374A5A",
    font=("Crimson Pro", 20 * -1)
)

canvas.create_text(
    741.0,
    777.0,
    anchor="nw",
    text="85%",
    fill="#374A5A",
    font=("Crimson Pro", 20 * -1)
)

image_image_9 = PhotoImage(
    file=relative_to_assets("image_9.png"))
image_9 = canvas.create_image(
    890.0,
    788.0,
    image=image_image_9
)

canvas.create_text(
    1075.0,
    778.0,
    anchor="nw",
    text="Premium",
    fill="#374A5A",
    font=("Crimson Pro", 20 * -1)
)

canvas.create_text(
    408.0,
    778.0,
    anchor="nw",
    text="C001",
    fill="#374A5A",
    font=("Crimson Pro", 20 * -1)
)

canvas.create_text(
    741.0,
    777.0,
    anchor="nw",
    text="85%",
    fill="#374A5A",
    font=("Crimson Pro", 20 * -1)
)

image_image_10 = PhotoImage(
    file=relative_to_assets("image_10.png"))
image_10 = canvas.create_image(
    890.0,
    827.0,
    image=image_image_10
)

canvas.create_text(
    1075.0,
    817.0,
    anchor="nw",
    text="Premium",
    fill="#374A5A",
    font=("Crimson Pro", 20 * -1)
)

canvas.create_text(
    408.0,
    817.0,
    anchor="nw",
    text="C001",
    fill="#374A5A",
    font=("Crimson Pro", 20 * -1)
)

canvas.create_text(
    741.0,
    816.0,
    anchor="nw",
    text="85%",
    fill="#374A5A",
    font=("Crimson Pro", 20 * -1)
)

image_image_11 = PhotoImage(
    file=relative_to_assets("image_11.png"))
image_11 = canvas.create_image(
    890.0,
    866.0,
    image=image_image_11
)

canvas.create_text(
    1075.0,
    856.0,
    anchor="nw",
    text="Premium",
    fill="#374A5A",
    font=("Crimson Pro", 20 * -1)
)

canvas.create_text(
    408.0,
    856.0,
    anchor="nw",
    text="C001",
    fill="#374A5A",
    font=("Crimson Pro", 20 * -1)
)

canvas.create_text(
    741.0,
    855.0,
    anchor="nw",
    text="85%",
    fill="#374A5A",
    font=("Crimson Pro", 20 * -1)
)

image_image_12 = PhotoImage(
    file=relative_to_assets("image_12.png"))
image_12 = canvas.create_image(
    890.0,
    905.0,
    image=image_image_12
)

canvas.create_text(
    1075.0,
    895.0,
    anchor="nw",
    text="Premium",
    fill="#374A5A",
    font=("Crimson Pro", 20 * -1)
)

canvas.create_text(
    408.0,
    895.0,
    anchor="nw",
    text="C001",
    fill="#374A5A",
    font=("Crimson Pro", 20 * -1)
)

canvas.create_text(
    741.0,
    894.0,
    anchor="nw",
    text="85%",
    fill="#374A5A",
    font=("Crimson Pro", 20 * -1)
)

image_image_13 = PhotoImage(
    file=relative_to_assets("image_13.png"))
image_13 = canvas.create_image(
    890.0,
    944.0,
    image=image_image_13
)

canvas.create_text(
    1075.0,
    934.0,
    anchor="nw",
    text="Premium",
    fill="#374A5A",
    font=("Crimson Pro", 20 * -1)
)

canvas.create_text(
    408.0,
    934.0,
    anchor="nw",
    text="C001",
    fill="#374A5A",
    font=("Crimson Pro", 20 * -1)
)

canvas.create_text(
    741.0,
    933.0,
    anchor="nw",
    text="85%",
    fill="#374A5A",
    font=("Crimson Pro", 20 * -1)
)

button_image_9 = PhotoImage(
    file=relative_to_assets("button_Delivery.png"))
button_Delivery = Button(
    image=button_image_9,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_Delivery clicked"),
    relief="flat"
)
button_Delivery.place(
    x=0.0,
    y=551.0,
    width=339.0,
    height=89.0
)
window.resizable(False, False)
window.mainloop()
