
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
from tkinter import Toplevel, Label, Frame  # này mới thêm nè

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("assets_Frame06")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)
#sửa từ đây nè má
def show_dropdown():
    # Nếu dropdown đã mở thì đóng trước
    for widget in window.winfo_children():
        if isinstance(widget, Toplevel):
            widget.destroy()

    # === Tạo popup dropdown ===
    dropdown = Toplevel(window)
    dropdown.overrideredirect(True)  # Bỏ viền cửa sổ
    dropdown.configure(bg="#FFFFFF")
    dropdown.attributes('-topmost', True)
    # Lấy vị trí button_2
    x = button_Profile.winfo_rootx()
    y = button_Profile.winfo_rooty() + button_Profile.winfo_height()

    dropdown.geometry(f"150x80+{x-100}+{y+5}")  # Điều chỉnh vị trí

    dropdown.update_idletasks()
    dropdown.lift()

    frame = Frame(dropdown, bg="#FFFFFF", highlightthickness=0)
    frame.pack(fill="both", expand=True, padx=5, pady=5)
    # Nút Account Info
    account_btn = Button(
        frame,
        text="Account Info",
        bg="#FFFFFF",
        fg="#5A3372",
        font=("Crimson Pro", 12, "bold"),
        anchor="w",
        relief="flat",
        command=lambda: print("Account Info clicked")
    )
    account_btn.pack(fill="x", pady=(5, 0), padx=10)

    # Nút Log out
    logout_btn = Button(
        frame,
        text="Log Out",
        bg="#FFFFFF",
        fg="#5A3372",
        font=("Crimson Pro", 12, "bold"),
        anchor="w",
        relief="flat",
        command=lambda: print("Logged out")
    )
    logout_btn.pack(fill="x", pady=(5, 5), padx=10)

    # Đóng dropdown khi click ra ngoài
    window.bind("<Button-1>", lambda e: close_dropdown(e, dropdown))

def close_dropdown(event, popup):
    # Nếu click không nằm trong popup
    if popup and not (popup.winfo_x() <= event.x_root <= popup.winfo_x() + popup.winfo_width() and
                      popup.winfo_y() <= event.y_root <= popup.winfo_y() + popup.winfo_height()):
        popup.destroy()




window = Tk()

window.geometry("1440x1024")
window.configure(bg = "#D4C5D2")


canvas = Canvas(
    window,
    bg = "#D4C5D2",
    height = 1024,
    width = 1440,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    168.0,
    512.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    1.0,
    245.0,
    image=image_image_2
)

canvas.create_text(
    98.0,
    927.0,
    anchor="nw",
    text="ChuLiBi",
    fill="#FDE5F4",
    font=("Rubik Burned", 35 * -1)
)

canvas.create_text(
    1142.0,
    972.0,
    anchor="nw",
    text="Copyright by ChuLiBi",
    fill="#706093",
    font=("Young Serif", 22 * -1)
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    889.0,
    202.0,
    image=image_image_3
)

canvas.create_text(
    399.0,
    125.0,
    anchor="nw",
    text="KPI cards",
    fill="#706093",
    font=("Young Serif", 24 * -1)
)

canvas.create_text(
    542.0,
    133.0,
    anchor="nw",
    text="Top Metrics",
    fill="#B992B9",
    font=("Crimson Pro", 17 * -1)
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    452.0,
    220.0,
    image=image_image_4
)

image_image_5 = PhotoImage(
    file=relative_to_assets("image_5.png"))
image_5 = canvas.create_image(
    577.0,
    220.0,
    image=image_image_5
)

image_image_6 = PhotoImage(
    file=relative_to_assets("image_6.png"))
image_6 = canvas.create_image(
    702.0,
    220.0,
    image=image_image_6
)

image_image_7 = PhotoImage(
    file=relative_to_assets("image_7.png"))
image_7 = canvas.create_image(
    827.0,
    220.0,
    image=image_image_7
)

image_image_8 = PhotoImage(
    file=relative_to_assets("image_8.png"))
image_8 = canvas.create_image(
    952.0,
    220.0,
    image=image_image_8
)

image_image_9 = PhotoImage(
    file=relative_to_assets("image_9.png"))
image_9 = canvas.create_image(
    1077.0,
    220.0,
    image=image_image_9
)

image_image_10 = PhotoImage(
    file=relative_to_assets("image_10.png"))
image_10 = canvas.create_image(
    1202.0,
    220.0,
    image=image_image_10
)

image_image_11 = PhotoImage(
    file=relative_to_assets("image_11.png"))
image_11 = canvas.create_image(
    1327.0,
    220.0,
    image=image_image_11
)

canvas.create_text(
    458.0,
    184.0,
    anchor="nw",
    text="500",
    fill="#634D94",
    font=("Kodchasan Bold", 15 * -1)
)

canvas.create_text(
    405.0,
    230.841552734375,
    anchor="nw",
    text="Total customers",
    fill="#634D94",
    font=("Crimson Pro", 15 * -1)
)

canvas.create_text(
    454.0,
    203.0,
    anchor="nw",
    text="(people)",
    fill="#B992B9",
    font=("Crimson Pro", 13 * -1)
)

canvas.create_text(
    444.0,
    248.841552734375,
    anchor="nw",
    text="Rows",
    fill="#AF96B9",
    font=("Crimson Pro", 12 * -1)
)

image_image_12 = PhotoImage(
    file=relative_to_assets("image_12.png"))
image_12 = canvas.create_image(
    426.0,
    199.0,
    image=image_image_12
)

canvas.create_text(
    585.0,
    184.0,
    anchor="nw",
    text="30",
    fill="#634D94",
    font=("Kodchasan Bold", 15 * -1)
)

canvas.create_text(
    543.0,
    229.0,
    anchor="nw",
    text="Average Age",
    fill="#634D94",
    font=("Crimson Pro", 15 * -1)
)

canvas.create_text(
    570.0,
    249.0,
    anchor="nw",
    text="Age",
    fill="#AF96B9",
    font=("Crimson Pro", 12 * -1)
)

canvas.create_text(
    574.0,
    203.0,
    anchor="nw",
    text="(years old)",
    fill="#B992B9",
    font=("Crimson Pro", 13 * -1)
)

image_image_13 = PhotoImage(
    file=relative_to_assets("image_13.png"))
image_13 = canvas.create_image(
    550.0,
    199.0,
    image=image_image_13
)

canvas.create_text(
    704.0,
    183.0,
    anchor="nw",
    text="2222",
    fill="#634D94",
    font=("Kodchasan Bold", 15 * -1)
)

canvas.create_text(
    664.0,
    228.0,
    anchor="nw",
    text="Total Orders",
    fill="#634D94",
    font=("Crimson Pro", 15 * -1)
)

canvas.create_text(
    655.0,
    248.0,
    anchor="nw",
    text="No. of orders placed",
    fill="#A08CB1",
    font=("Crimson Pro", 12 * -1)
)

canvas.create_text(
    700.0,
    203.0,
    anchor="nw",
    text="(orders)",
    fill="#8D6B8D",
    font=("Crimson Pro", 13 * -1)
)

canvas.create_text(
    832.0,
    184.0,
    anchor="nw",
    text="222",
    fill="#634D94",
    font=("Kodchasan Bold", 15 * -1)
)

canvas.create_text(
    780.0,
    210.0,
    anchor="nw",
    text="High-Frequency \nCustomer Rate",
    fill="#634D94",
    font=("Crimson Pro", 13 * -1)
)

canvas.create_text(
    781.0,
    240.0,
    anchor="nw",
    text="CustomerID; \nNo. of orders placed",
    fill="#9282AA",
    font=("Crimson Pro", 12 * -1)
)

canvas.create_text(
    838.0,
    200.0,
    anchor="nw",
    text="(%)",
    fill="#794679",
    font=("Crimson Pro", 13 * -1)
)

canvas.create_text(
    950.0,
    186.0,
    anchor="nw",
    text="$200",
    fill="#FDE5F4",
    font=("Kodchasan Bold", 15 * -1)
)

canvas.create_text(
    906.0,
    215.0,
    anchor="nw",
    text="Average Order \nValue",
    fill="#FFFFFF",
    font=("Crimson Pro", 15 * -1)
)

canvas.create_text(
    932.0,
    254.0,
    anchor="nw",
    text="Order Value",
    fill="#D9D9D9",
    font=("Crimson Pro", 12 * -1)
)

canvas.create_text(
    1082.0,
    183.0,
    anchor="nw",
    text="2.5",
    fill="#FDE5F4",
    font=("Kodchasan Bold", 15 * -1)
)

canvas.create_text(
    1025.0,
    218.0,
    anchor="nw",
    text="Average Delivery \nTime",
    fill="#FFFFFF",
    font=("Crimson Pro", 15 * -1)
)

canvas.create_text(
    1050.0,
    253.0,
    anchor="nw",
    text="Delivery Time",
    fill="#D9D9D9",
    font=("Crimson Pro", 12 * -1)
)

canvas.create_text(
    1075.0,
    202.0,
    anchor="nw",
    text="(hours)",
    fill="#D9D9D9",
    font=("Crimson Pro", 13 * -1)
)

canvas.create_text(
    1211.671875,
    187.0,
    anchor="nw",
    text="4",
    fill="#FDE5F4",
    font=("Kodchasan Bold", 15 * -1)
)

canvas.create_text(
    1156.0,
    225.0,
    anchor="nw",
    text="Average Rating",
    fill="#FFFFFF",
    font=("Crimson Pro", 15 * -1)
)

canvas.create_text(
    1160.0,
    250.0,
    anchor="nw",
    text="Restaurant Rating\n\n",
    fill="#D9D9D9",
    font=("Crimson Pro", 12 * -1)
)

canvas.create_text(
    1330.0,
    187.0,
    anchor="nw",
    text="4.5",
    fill="#FDE5F4",
    font=("Kodchasan Bold", 15 * -1)
)

canvas.create_text(
    1281.0,
    224.0,
    anchor="nw",
    text="Average Rating",
    fill="#FFFFFF",
    font=("Crimson Pro", 15 * -1)
)

canvas.create_text(
    1294.0,
    250.0,
    anchor="nw",
    text="Delivery Rating\n",
    fill="#D9D9D9",
    font=("Crimson Pro", 12 * -1)
)

image_image_14 = PhotoImage(
    file=relative_to_assets("image_14.png"))
image_14 = canvas.create_image(
    676.0,
    199.0,
    image=image_image_14
)

image_image_15 = PhotoImage(
    file=relative_to_assets("image_15.png"))
image_15 = canvas.create_image(
    801.0,
    195.0,
    image=image_image_15
)

image_image_16 = PhotoImage(
    file=relative_to_assets("image_16.png"))
image_16 = canvas.create_image(
    633.0,
    469.0,
    image=image_image_16
)

canvas.create_text(
    405.0,
    322.0,
    anchor="nw",
    text="Bar chart",
    fill="#706093",
    font=("Young Serif", 27 * -1)
)

canvas.create_text(
    544.0,
    335.0,
    anchor="nw",
    text="Customer group with the highest spending",
    fill="#B992B9",
    font=("Crimson Pro", 18 * -1)
)

image_image_17 = PhotoImage(
    file=relative_to_assets("image_17.png"))
image_17 = canvas.create_image(
    1151.0,
    469.0,
    image=image_image_17
)

canvas.create_text(
    937.0,
    324.0,
    anchor="nw",
    text="Histogram chart",
    fill="#706093",
    font=("Young Serif", 27 * -1)
)

canvas.create_text(
    1180.0,
    324.0,
    anchor="nw",
    text="Delivery Performance \nImpact of Late Delivery",
    fill="#B992B9",
    font=("Crimson Pro", 18 * -1)
)

image_image_18 = PhotoImage(
    file=relative_to_assets("image_18.png"))
image_18 = canvas.create_image(
    664.0,
    802.0,
    image=image_image_18
)

canvas.create_text(
    407.0,
    659.0,
    anchor="nw",
    text="Line chart",
    fill="#706093",
    font=("Young Serif", 27 * -1)
)

canvas.create_text(
    560.0,
    674.0,
    anchor="nw",
    text="Order Trends by Age Group",
    fill="#B992B9",
    font=("Crimson Pro", 18 * -1)
)

image_image_19 = PhotoImage(
    file=relative_to_assets("image_19.png"))
image_19 = canvas.create_image(
    1184.0,
    802.0,
    image=image_image_19
)

canvas.create_text(
    999.0,
    659.0,
    anchor="nw",
    text="Pie chart",
    fill="#706093",
    font=("Young Serif", 27 * -1)
)

canvas.create_text(
    1135.0,
    673.0,
    anchor="nw",
    text="Proportion of Meal Types",
    fill="#B992B9",
    font=("Crimson Pro", 18 * -1)
)

image_image_20 = PhotoImage(
    file=relative_to_assets("image_20.png"))
image_20 = canvas.create_image(
    888.0,
    42.0,
    image=image_image_20
)

canvas.create_text(
    373.0,
    16.0,
    anchor="nw",
    text="Dashboard",
    fill="#000000",
    font=("Young Serif", 40 * -1)
)

image_image_21 = PhotoImage(
    file=relative_to_assets("image_21.png"))
image_21 = canvas.create_image(
    162.0,
    101.0,
    image=image_image_21
)

image_image_22 = PhotoImage(
    file=relative_to_assets("image_22.png"))
image_22 = canvas.create_image(
    924.0,
    198.0,
    image=image_image_22
)

image_image_23 = PhotoImage(
    file=relative_to_assets("image_23.png"))
image_23 = canvas.create_image(
    1050.0,
    197.0,
    image=image_image_23
)

image_image_24 = PhotoImage(
    file=relative_to_assets("image_24.png"))
image_24 = canvas.create_image(
    1181.0,
    196.0,
    image=image_image_24
)

image_image_25 = PhotoImage(
    file=relative_to_assets("image_25.png"))
image_25 = canvas.create_image(
    1303.0,
    196.0,
    image=image_image_25
)

image_image_26 = PhotoImage(
    file=relative_to_assets("image_26.png"))
image_26 = canvas.create_image(
    1296.0,
    42.0,
    image=image_image_26
)

button_Dashboard_image = PhotoImage(
    file=relative_to_assets("button_Dashboard.png"))
button_Dashboard = Button(
    image=button_Dashboard_image,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_Dashboard clicked"),
    relief="flat"
)
button_Dashboard.place(
    x=20.0,
    y=201.0,
    width=317.0,
    height=87.0
)

button_Profile_image = PhotoImage(
    file=relative_to_assets("button_Profile.png"))
button_Profile = Button(
    image=button_Profile_image,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_Profile clicked"),
    relief="flat"
)
button_Profile.place(
    x=1332.0,
    y=16.0,
    width=57.0,
    height=51.0
)

button_Customer_analysis_image = PhotoImage(
    file=relative_to_assets("button_Customer_analysis.png"))
button_Customer_analysis = Button(
    image=button_Customer_analysis_image,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_Customer_analysis"),
    relief="flat"
)
button_Customer_analysis.place(
    x=0.0,
    y=302.0,
    width=337.0,
    height=77.0
)

button_Recommendation_image = PhotoImage(
    file=relative_to_assets("button_Recommendation.png"))
button_Recommendation = Button(
    image=button_Recommendation_image,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_Recommendation clicked"),
    relief="flat"
)
button_Recommendation.place(
    x=0.0,
    y=468.0,
    width=336.0,
    height=82.0
)

button_Churn_image = PhotoImage(
    file=relative_to_assets("button_Churn.png"))
button_Churn = Button(
    image=button_Churn_image,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_Churn clicked"),
    relief="flat"
)
button_Churn.place(
    x=0.0,
    y=381.0,
    width=336.0,
    height=86.0
)

button_Delivery_image = PhotoImage(
    file=relative_to_assets("button_Delivery.png"))
button_Delivery = Button(
    image=button_Delivery_image,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_Delivery clicked"),
    relief="flat"
)
button_Delivery.place(
    x=0.0,
    y=552.0,
    width=337.0,
    height=90.0
)
button_Report_image = PhotoImage(
    file=relative_to_assets("button_Report.png"))
button_Report = Button(
    image=button_Report_image,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_Report clicked"),
    relief="flat"
)
button_Report.place(
    x=0.0,
    y=646.0,
    width=338.0,
    height=88.0
)

# Gán sự kiện click vào icon người dùng
button_Profile.configure(command=show_dropdown)
window.resizable(False, False)
window.mainloop()
