
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("assets_Frame13")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1440x1024")
window.configure(bg = "#D4C5D2")


canvas = Canvas(
    window,
    bg = "#D4C5D2",
    height = 1024,
    width = 1440,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_text(
    98.0,
    927.0,
    anchor="nw",
    text="ChuLiBi",
    fill="#FDE5F4",
    font=("Rubik Burned Regular", 35 * -1)
)

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    889.0,
    194.0,
    image=image_image_1
)

canvas.create_text(
    399.0,
    122.0,
    anchor="nw",
    text="Import Data",
    fill="#706093",
    font=("Young Serif", 26 * -1)
)

canvas.create_text(
    399.0,
    162.0,
    anchor="nw",
    text="Choose Data File (CSV/JSON)",
    fill="#B992B9",
    font=("Crimson Pro", 20 * -1)
)

canvas.create_text(
    1051.0,
    162.0,
    anchor="nw",
    text="Or you can see the Reference File: ",
    fill="#B992B9",
    font=("Crimson Pro", 20 * -1)
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    888.0,
    639.0,
    image=image_image_2
)

canvas.create_text(
    408.0,
    318.0,
    anchor="nw",
    text="Data List",
    fill="#706093",
    font=("Young Serif", 26 * -1)
)

canvas.create_text(
    903.0,
    371.0,
    anchor="nw",
    text="Search:",
    fill="#B992B9",
    font=("Crimson Pro", 20 * -1)
)

canvas.create_text(
    120.0,
    919.0,
    anchor="nw",
    text="ChuLiBi",
    fill="#FDE5F4",
    font=("Rubik Burned Regular", 35 * -1)
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    168.0,
    513.0,
    image=image_image_3
)

canvas.create_text(
    98.0,
    928.0,
    anchor="nw",
    text="ChuLiBi",
    fill="#FDE5F4",
    font=("Rubik Burned Regular", 35 * -1)
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    162.0,
    102.0,
    image=image_image_4
)

button_image_CustomerAnalysis = PhotoImage(
    file=relative_to_assets("button_CustomerAnalysis.png"))
button_CustomerAnalysis = Button(
    image=button_image_CustomerAnalysis,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_CustomerAnalysis clicked"),
    relief="flat"
)
button_CustomerAnalysis.place(
    x=0.0,
    y=303.0,
    width=337.0,
    height=77.0
)

button_image_Recommendation = PhotoImage(
    file=relative_to_assets("button_Recommendation.png"))
button_Recommendation = Button(
    image=button_image_Recommendation,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_Recommendation clicked"),
    relief="flat"
)
button_Recommendation.place(
    x=0.0,
    y=469.0,
    width=336.0,
    height=82.0
)

button_image_Churn = PhotoImage(
    file=relative_to_assets("button_Churn.png"))
button_Churn = Button(
    image=button_image_Churn,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_Churn clicked"),
    relief="flat"
)
button_Churn.place(
    x=0.0,
    y=382.0,
    width=336.0,
    height=86.0
)

button_image_Delivery = PhotoImage(
    file=relative_to_assets("button_Delivery.png"))
button_Delivery = Button(
    image=button_image_Delivery,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_Delivery clicked"),
    relief="flat"
)
button_Delivery.place(
    x=0.0,
    y=553.0,
    width=337.0,
    height=90.0
)

button_image_Dashboard = PhotoImage(
    file=relative_to_assets("button_Dashboard.png"))
button_Dashboard = Button(
    image=button_image_Dashboard,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_Dashboard clicked"),
    relief="flat"
)
button_Dashboard.place(
    x=0.0,
    y=222.0,
    width=337.0,
    height=79.0
)

image_image_5 = PhotoImage(
    file=relative_to_assets("image_5.png"))
image_5 = canvas.create_image(
    887.0,
    42.0,
    image=image_image_5
)

canvas.create_text(
    381.0,
    14.0,
    anchor="nw",
    text="Data Management",
    fill="#000000",
    font=("Young Serif", 40 * -1)
)

button_image_Profile = PhotoImage(
    file=relative_to_assets("button_Profile.png"))
button_Profile = Button(
    image=button_image_Profile,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_Profile clicked"),
    relief="flat"
)
button_Profile.place(
    x=1360.0,
    y=17.0,
    width=44.0,
    height=45.0
)

image_image_6 = PhotoImage(
    file=relative_to_assets("image_6.png"))
image_6 = canvas.create_image(
    1321.0,
    42.0,
    image=image_image_6
)

canvas.create_text(
    765.0,
    50.0,
    anchor="nw",
    text="View and import customer or order data",
    fill="#FFFFFF",
    font=("Crimson Pro", 18 * -1)
)

image_image_7 = PhotoImage(
    file=relative_to_assets("image_7.png"))
image_7 = canvas.create_image(
    573.0,
    221.0,
    image=image_image_7
)

canvas.create_text(
    577.0,
    210.0,
    anchor="nw",
    text="No file chosen",
    fill="#B992B9",
    font=("Crimson Pro", 20 * -1)
)

button_image_ChooseFile = PhotoImage(
    file=relative_to_assets("button_ChooseFile.png"))
button_ChooseFile = Button(
    image=button_image_ChooseFile,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_ChooseFile clicked"),
    relief="flat"
)
button_ChooseFile.place(
    x=408.0,
    y=207.0,
    width=153.0,
    height=28.0
)

button_image_ImportData = PhotoImage(
    file=relative_to_assets("button_ImportData.png"))
button_ImportData = Button(
    image=button_image_ImportData,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_ImportData clicked"),
    relief="flat"
)
button_ImportData.place(
    x=776.0,
    y=193.0,
    width=219.0,
    height=57.0
)

entry_image_Search = PhotoImage(
    file=relative_to_assets("entry_Search.png"))
entry_bg_1 = canvas.create_image(
    1153.5,
    382.5,
    image=entry_image_Search
)
entry_1 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0,
    font=("Crimson Pro", 18 * -1))
entry_1.place(
    x=986.0,
    y=362.0,
    width=335.0,
    height=39.0
)

canvas.create_text(
    767.0,
    512.0,
    anchor="nw",
    text="No data availavle in table...",
    fill="#B992B9",
    font=("Crimson Pro", 20 * -1)
)

image_image_8 = PhotoImage(
    file=relative_to_assets("image_8.png"))
image_8 = canvas.create_image(
    523.0,
    456.0,
    image=image_image_8
)

image_image_9 = PhotoImage(
    file=relative_to_assets("image_9.png"))
image_9 = canvas.create_image(
    669.0,
    456.0,
    image=image_image_9
)

image_image_10 = PhotoImage(
    file=relative_to_assets("image_10.png"))
image_10 = canvas.create_image(
    815.0,
    456.0,
    image=image_image_10
)

image_image_11 = PhotoImage(
    file=relative_to_assets("image_11.png"))
image_11 = canvas.create_image(
    961.0,
    456.0,
    image=image_image_11
)

image_image_12 = PhotoImage(
    file=relative_to_assets("image_12.png"))
image_12 = canvas.create_image(
    1107.0,
    456.0,
    image=image_image_12
)

image_image_13 = PhotoImage(
    file=relative_to_assets("image_13.png"))
image_13 = canvas.create_image(
    1253.0,
    456.0,
    image=image_image_13
)

canvas.create_rectangle(
    416.0,
    949.0000001466271,
    1358.9999881741605,
    953.0,
    fill="#E0E0E0",
    outline="")

canvas.create_text(
    484.0,
    445.0,
    anchor="nw",
    text="Variable 1",
    fill="#FFFFFF",
    font=("Young Serif", 16 * -1)
)

canvas.create_text(
    630.0,
    445.0,
    anchor="nw",
    text="Variable 2",
    fill="#FFFFFF",
    font=("Young Serif", 16 * -1)
)

canvas.create_text(
    776.0,
    445.0,
    anchor="nw",
    text="Variable 3",
    fill="#FFFFFF",
    font=("Young Serif", 16 * -1)
)

canvas.create_text(
    922.0,
    445.0,
    anchor="nw",
    text="Variable 4",
    fill="#FFFFFF",
    font=("Young Serif", 16 * -1)
)

canvas.create_text(
    1068.0,
    445.0,
    anchor="nw",
    text="Variable 5",
    fill="#FFFFFF",
    font=("Young Serif", 16 * -1)
)

canvas.create_text(
    1214.0,
    445.0,
    anchor="nw",
    text="Variable 6",
    fill="#FFFFFF",
    font=("Young Serif", 16 * -1)
)

button_image_ReferenceFile = PhotoImage(
    file=relative_to_assets("button_ReferenceFile.png"))
button_ReferenceFile = Button(
    image=button_image_ReferenceFile,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_ReferenceFile clicked"),
    relief="flat"
)
button_ReferenceFile.place(
    x=1090.0,
    y=192.0,
    width=236.0,
    height=58.0
)

button_image_Report = PhotoImage(
    file=relative_to_assets("button_Report.png"))
button_Report = Button(
    image=button_image_Report,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_Report clicked"),
    relief="flat"
)
button_Report.place(
    x=0.0,
    y=643.0,
    width=338.0,
    height=88.0
)

image_image_14 = PhotoImage(
    file=relative_to_assets("image_14.png"))
image_14 = canvas.create_image(
    1396.0,
    570.0,
    image=image_image_14
)

image_image_15 = PhotoImage(
    file=relative_to_assets("image_15.png"))
image_15 = canvas.create_image(
    509.0,
    945.0,
    image=image_image_15
)
window.resizable(False, False)
window.mainloop()
