
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH /  Path("assets_Frame05")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1440x1024")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 1024,
    width = 1440,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    360.0,
    512.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    360.0,
    512.0,
    image=image_image_2
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    1081.0,
    513.0,
    image=image_image_3
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    720.0,
    512.0,
    image=image_image_4
)

canvas.create_text(
    839.0,
    115.0,
    anchor="nw",
    text="Reset Password",
    fill="#000000",
    font=("Young Serif", 55 * -1)
)

canvas.create_text(
    906.0,
    418.0,
    anchor="nw",
    text="New Password",
    fill="#000000",
    font=("Crimson Pro SemiBold", 28 * -1)
)

entry_image_newpassword = PhotoImage(
    file=relative_to_assets("entry_newpassword.png"))
entry_bg_1 = canvas.create_image(
    1083.5,
    488.5,
    image=entry_image_newpassword
)
entry_newpassword = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0,
    font=("Crimson Pro Regular", 26 * -1)
)
entry_newpassword.place(
    x=859.0,
    y=454.0,
    width=449.0,
    height=67.0
)

image_image_5 = PhotoImage(
    file=relative_to_assets("image_5.png"))
image_5 = canvas.create_image(
    877.0,
    435.0,
    image=image_image_5
)

image_image_6 = PhotoImage(
    file=relative_to_assets("image_6.png"))
image_6 = canvas.create_image(
    876.0,
    573.0,
    image=image_image_6
)

image_image_7 = PhotoImage(
    file=relative_to_assets("image_7.png"))
image_7 = canvas.create_image(
    878.0,
    422.0,
    image=image_image_7
)

image_image_8 = PhotoImage(
    file=relative_to_assets("image_8.png"))
image_8 = canvas.create_image(
    877.0,
    560.0,
    image=image_image_8
)

canvas.create_text(
    900.0,
    559.0,
    anchor="nw",
    text="Confirm password",
    fill="#000000",
    font=("Crimson Pro SemiBold", 28 * -1)
)

canvas.create_text(
    900.0,
    682.0,
    anchor="nw",
    text="OTP-Verify",
    fill="#000000",
    font=("Crimson Pro SemiBold", 28 * -1)
)

entry_image_confirm_password = PhotoImage(
    file=relative_to_assets("entry_confirm_password.png"))
entry_bg_2 = canvas.create_image(
    1083.5,
    627.5,
    image=entry_image_confirm_password
)
entry_confirm_newpassword = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0,
    font=("Crimson Pro Regular", 26 * -1)
)
entry_confirm_newpassword.place(
    x=859.0,
    y=593.0,
    width=449.0,
    height=67.0
)

entry_image_OTP = PhotoImage(
    file=relative_to_assets("entry_OTP.png"))
entry_bg_3 = canvas.create_image(
    1083.5,
    750.5,
    image=entry_image_OTP
)
entry_OTP = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0,
    font=("Crimson Pro Regular", 26 * -1)
)
entry_OTP.place(
    x=859.0,
    y=716.0,
    width=449.0,
    height=67.0
)

canvas.create_text(
    280.0,
    900.0,
    anchor="nw",
    text="ChuLiBi",
    fill="#FDE5F4",
    font=("Rubik Burned Regular", 35 * -1)
)

canvas.create_text(
    21.0,
    477.0,
    anchor="nw",
    text="Secure your account",
    fill="#FFFFFF",
    font=("Young Serif", 65 * -1)
)

canvas.create_text(
    162.0,
    597.0,
    anchor="nw",
    text="Reset your password ",
    fill="#FFFFFF",
    font=("Crimson Pro SemiBold", 40 * -1)
)

canvas.create_text(
    39.0,
    647.0,
    anchor="nw",
    text="continue your AI journey with ChuLiBi",
    fill="#FFFFFF",
    font=("Crimson Pro SemiBold", 40 * -1)
)

canvas.create_text(
    903.0,
    271.0,
    anchor="nw",
    text="Username",
    fill="#000000",
    font=("Crimson Pro SemiBold", 28 * -1)
)

image_image_9 = PhotoImage(
    file=relative_to_assets("image_9.png"))
image_9 = canvas.create_image(
    875.0,
    287.0,
    image=image_image_9
)

image_image_10 = PhotoImage(
    file=relative_to_assets("image_10.png"))
image_10 = canvas.create_image(
    875.0,
    270.0,
    image=image_image_10
)

entry_image_username = PhotoImage(
    file=relative_to_assets("entry_username.png"))
entry_bg_4 = canvas.create_image(
    1083.5,
    341.0,
    image=entry_image_username
)
entry_username = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0,
    font=("Crimson Pro Regular", 26 * -1)
)
entry_username.place(
    x=859.0,
    y=306.5,
    width=449.0,
    height=67.0
)

button_image_eyes_password = PhotoImage(
    file=relative_to_assets("button_eyes.png"))
button_eyes_password = Button(
    image=button_image_eyes_password,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_eyes _password clicked"),
    relief="flat"
)
button_eyes_password.place(
    x=1270.0,
    y=476.0,
    width=30.0,
    height=21.0
)

button_image_eyes = PhotoImage(
    file=relative_to_assets("button_eyes.png"))
button_eyes = Button(
    image=button_image_eyes,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_eyes 2 clicked"),
    relief="flat"
)
button_eyes.place(
    x=1270.0,
    y=617.0,
    width=30.0,
    height=21.0
)

image_image_11 = PhotoImage(
    file=relative_to_assets("image_11.png"))
image_11 = canvas.create_image(
    875.875,
    692.875,
    image=image_image_11
)

image_image_12 = PhotoImage(
    file=relative_to_assets("image_12.png"))
image_12 = canvas.create_image(
    876.458251953125,
    694.25,
    image=image_image_12
)

image_image_13 = PhotoImage(
    file=relative_to_assets("image_13.png"))
image_13 = canvas.create_image(
    869.75,
    693.25,
    image=image_image_13
)

image_image_14 = PhotoImage(
    file=relative_to_assets("image_14.png"))
image_14 = canvas.create_image(
    876.208251953125,
    693.25,
    image=image_image_14
)

image_image_15 = PhotoImage(
    file=relative_to_assets("image_15.png"))
image_15 = canvas.create_image(
    882.666748046875,
    693.25,
    image=image_image_15
)

image_image_16 = PhotoImage(
    file=relative_to_assets("image_16.png"))
image_16 = canvas.create_image(
    357.0,
    350.0,
    image=image_image_16
)

button_image_resetpassword = PhotoImage(
    file=relative_to_assets("button_resetpassword.png"))
button_resetpassword = Button(
    image=button_image_resetpassword,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_resetpassword clicked"),
    relief="flat"
)
button_resetpassword.place(
    x=844.0,
    y=817.0,
    width=484.0,
    height=67.0
)
window.resizable(False, False)
window.mainloop()
