
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("assets_Frame03")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1440x1024")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 1024,
    width = 1440,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    360.0,
    512.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    360.0,
    512.0,
    image=image_image_2
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    1081.0,
    533.0,
    image=image_image_3
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    720.0,
    512.0,
    image=image_image_4
)

canvas.create_text(
    913.0,
    277.0,
    anchor="nw",
    text="Your Profile",
    fill="#000000",
    font=("Young Serif", 55 * -1)
)

canvas.create_text(
    948.0,
    179.0,
    anchor="nw",
    text="Complete ",
    fill="#000000",
    font=("Young Serif", 55 * -1)
)

image_image_5 = PhotoImage(
    file=relative_to_assets("image_5.png"))
image_5 = canvas.create_image(
    360.0,
    334.0,
    image=image_image_5
)

canvas.create_text(
    153.0,
    466.0,
    anchor="nw",
    text="Almost there!",
    fill="#FFFFFF",
    font=("Young Serif", 60 * -1)
)

canvas.create_text(
    39.0,
    565.0,
    anchor="nw",
    text=" A few details help ChuLiBi personalize ",
    fill="#FFFFFF",
    font=("Crimson Pro SemiBold", 40 * -1)
)

canvas.create_text(
    132.0,
    615.0,
    anchor="nw",
    text="insights for your business.",
    fill="#FFFFFF",
    font=("Crimson Pro SemiBold", 40 * -1)
)

canvas.create_text(
    908.0,
    686.0,
    anchor="nw",
    text="Your Role",
    fill="#000000",
    font=("Crimson Pro SemiBold", 28 * -1)
)

entry_image_yourrole = PhotoImage(
    file=relative_to_assets("entry_full_name.png"))
entry_bg_1 = canvas.create_image(
    1081.5,
    755.5,
    image=entry_image_yourrole
)
entry_your_role = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0,
    font=("Crimson Pro Regular", 26 * -1)
)
entry_your_role.place(
    x=857.0,
    y=721.0,
    width=449.0,
    height=67.0
)

canvas.create_text(
    908,
    409,
    anchor="nw",
    text="FullName",
    fill="#000000",
    font=("Crimson Pro SemiBold", 28 * -1)
)

entry_image_fullname = PhotoImage(
    file=relative_to_assets("entry_full_name.png"))
entry_bg_2 = canvas.create_image(
    1081.5,
    484.5,
    image=entry_image_fullname
)
entry_full_name = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0,
    font=("Crimson Pro Regular", 26 * -1)
)
entry_full_name.place(
    x=857.0,
    y=450.0,
    width=449.0,
    height=67.0
)

image_image_6 = PhotoImage(
    file=relative_to_assets("image_6.png"))
image_6 = canvas.create_image(
    872.0,
    427.0,
    image=image_image_6
)

image_image_7 = PhotoImage(
    file=relative_to_assets("image_7.png"))
image_7 = canvas.create_image(
    873.0,
    409.0,
    image=image_image_7
)

canvas.create_text(
    908.0,
    545.0,
    anchor="nw",
    text="Business Name",
    fill="#000000",
    font=("Crimson Pro SemiBold", 28 * -1)
)

entry_image_business_name = PhotoImage(
    file=relative_to_assets("entry_business_name.png"))
entry_bg_business = canvas.create_image(
    1081.5,
    618.5,
    image=entry_image_business_name
)
entry_business_name = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0,
    font=("Crimson Pro Regular", 26 * -1)
)
entry_business_name.place(
    x=857.0,
    y=584.0,
    width=449.0,
    height=67.0
)

button_image_continue = PhotoImage(
    file=relative_to_assets("button_continue.png"))
button_continue = Button(
    image=button_image_continue,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("clicked button continue"),
    relief="flat"
)
button_continue.place(
    x=843.0,
    y=822.0,
    width=482.0,
    height=69.0
)

image_image_8 = PhotoImage(
    file=relative_to_assets("image_8.png"))
image_8 = canvas.create_image(
    872.0,
    561.8333740234375,
    image=image_image_8
)

image_image_9 = PhotoImage(
    file=relative_to_assets("image_9.png"))
image_9 = canvas.create_image(
    872.0,
    563.291748046875,
    image=image_image_9
)

image_image_10 = PhotoImage(
    file=relative_to_assets("image_10.png"))
image_10 = canvas.create_image(
    871.25,
    551.0,
    image=image_image_10
)

image_image_11 = PhotoImage(
    file=relative_to_assets("image_11.png"))
image_11 = canvas.create_image(
    872.08349609375,
    561.0833740234375,
    image=image_image_11
)

image_image_12 = PhotoImage(
    file=relative_to_assets("image_12.png"))
image_12 = canvas.create_image(
    868.8125,
    691.0,
    image=image_image_12
)

image_image_13 = PhotoImage(
    file=relative_to_assets("image_13.png"))
image_13 = canvas.create_image(
    869.0,
    704.5,
    image=image_image_13
)

image_image_14 = PhotoImage(
    file=relative_to_assets("image_14.png"))
image_14 = canvas.create_image(
    881.75,
    696.90625,
    image=image_image_14
)
window.resizable(False, False)
window.mainloop()
