
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"assets_Frame08_1")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1424x1024")
window.configure(bg = "#D4C5D2")


canvas = Canvas(
    window,
    bg = "#D4C5D2",
    height = 1024,
    width = 1424,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    0.0,
    0.0,
    1440.0,
    1024.0,
    fill="#E6DDE4",
    outline="")

image_image_1 = PhotoImage(
    file=relative_to_assets("image_ScrollBar.png"))
image_1 = canvas.create_image(
    1409.0,
    249.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_ModelEvaluationMetricsChart.png"))
image_2 = canvas.create_image(
    880.0,
    828.0,
    image=image_image_2
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_SlideBar_C.png"))
image_3 = canvas.create_image(
    171.0,
    513.0,
    image=image_image_3
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_Churn_picked.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=1.0,
    y=381.0,
    width=337.0,
    height=88.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_CustomerAnalysis.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=0.0,
    y=304.0,
    width=337.0,
    height=57.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_Report.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=1.0,
    y=648.0,
    width=338.0,
    height=88.0
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_Delivery.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat"
)
button_4.place(
    x=0.0,
    y=558.0,
    width=337.0,
    height=90.0
)

button_image_5 = PhotoImage(
    file=relative_to_assets("button_Recommendation.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_5 clicked"),
    relief="flat"
)
button_5.place(
    x=0.0,
    y=478.0,
    width=337.0,
    height=73.0
)

button_image_6 = PhotoImage(
    file=relative_to_assets("button_Dashboard.png"))
button_6 = Button(
    image=button_image_6,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_6 clicked"),
    relief="flat"
)
button_6.place(
    x=0.0,
    y=202.0,
    width=337.0,
    height=72.0
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_Title.png"))
image_4 = canvas.create_image(
    881.0,
    34.0,
    image=image_image_4
)

image_image_5 = PhotoImage(
    file=relative_to_assets("image_Noti.png"))
image_5 = canvas.create_image(
    1300.0,
    32.0,
    image=image_image_5
)

image_image_6 = PhotoImage(
    file=relative_to_assets("image_Profile.png"))
image_6 = canvas.create_image(
    1368.0,
    32.0,
    image=image_image_6
)

image_image_7 = PhotoImage(
    file=relative_to_assets("image_ReasonsChart.png"))
image_7 = canvas.create_image(
    1222.0,
    444.0,
    image=image_image_7
)

image_image_8 = PhotoImage(
    file=relative_to_assets("image_ChurnRateByCustomerSegment.png"))
image_8 = canvas.create_image(
    680.0,
    444.0,
    image=image_image_8
)

image_image_9 = PhotoImage(
    file=relative_to_assets("image_BestModel.png"))
image_9 = canvas.create_image(
    1222.0,
    154.0,
    image=image_image_9
)

image_image_10 = PhotoImage(
    file=relative_to_assets("image_Clusters.png"))
image_10 = canvas.create_image(
    855.0,
    156.0,
    image=image_image_10
)

image_image_11 = PhotoImage(
    file=relative_to_assets("image_AvgChurn.png"))
image_11 = canvas.create_image(
    505.0,
    154.0,
    image=image_image_11
)
window.resizable(False, False)
window.mainloop()
