# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer

from pathlib import Path
import tkinter as tk
from tkinter import Canvas, Button, PhotoImage

# ===== Paths (theo file thứ 2) =====
OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("assets_Frame07")

def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

# ===== Window =====
window = tk.Tk()
window.geometry("1440x1024")
window.configure(bg="#FFFFFF")

# ===== Canvas =====
canvas = Canvas(
    window,
    bg="#FFFFFF",
    height=1024,
    width=1440,
    bd=0,
    highlightthickness=0,
    relief="ridge",
)
canvas.place(x=0, y=0)

# ===== Images (tên & toạ độ theo file 2, mỗi ảnh 1 biến riêng) =====
img_1 = PhotoImage(file=relative_to_assets("image_1.png"))
canvas.create_image(721.0, 516.0, image=img_1)

img_2 = PhotoImage(file=relative_to_assets("image_2.png"))
canvas.create_image(888.0, 43.0, image=img_2)

img_3 = PhotoImage(file=relative_to_assets("image_3.png"))
canvas.create_image(891.0, 828.0, image=img_3)

img_4 = PhotoImage(file=relative_to_assets("image_4.png"))
canvas.create_image(1276.0, 851.0, image=img_4)

img_5 = PhotoImage(file=relative_to_assets("image_5.png"))
canvas.create_image(1019.0, 851.0, image=img_5)

img_6 = PhotoImage(file=relative_to_assets("image_6.png"))
canvas.create_image(762.0, 851.0, image=img_6)

img_7 = PhotoImage(file=relative_to_assets("image_7.png"))
canvas.create_image(505.0, 851.0, image=img_7)

img_8 = PhotoImage(file=relative_to_assets("image_8.png"))
canvas.create_image(710.0, 373.0, image=img_8)

img_9 = PhotoImage(file=relative_to_assets("image_9.png"))
canvas.create_image(1246.0, 546.0, image=img_9)

img_10 = PhotoImage(file=relative_to_assets("image_10.png"))
canvas.create_image(1246.0, 263.0, image=img_10)

img_11 = PhotoImage(file=relative_to_assets("image_11.png"))
canvas.create_image(170.0, 512.0, image=img_11)

img_12 = PhotoImage(file=relative_to_assets("image_12.png"))
canvas.create_image(164.0, 101.0, image=img_12)

img_14 = PhotoImage(file=relative_to_assets("image_14.png"))
canvas.create_image(0, 341.0, image=img_14)

# ===== Text (font/toạ độ theo file 2) =====
canvas.create_text(
    333.0,
    15.0,
    anchor="nw",
    text="   Customer Segmentation",
    fill="#706093",
    font=("Young Serif", 40 * -1),
)


canvas.create_text(
    388.0,
    679.0,
    anchor="nw",
    text="Characteristics of Customer Segmentation",
    fill="#000000",
    font=("Young Serif", 20 * -1),
)

canvas.create_text(
    1167.0,
    842.0,
    anchor="nw",
    text="Feature 1\nFeature 2\nFeature 3\nFeature 4",
    fill="#000000",
    font=("Young Serif", 18 * -1),
)
canvas.create_text(1263.0, 799.0, anchor="nw", text="-", fill="#000000", font=("Kodchasan-Regular", 40 * -1))
canvas.create_text(1233.0, 743.0, anchor="nw", text="Cluster 4", fill="#2E136B", font=("Young Serif", 18 * -1))

canvas.create_text(
    910.0,
    842.0,
    anchor="nw",
    text="Feature 1\nFeature 2\nFeature 3\nFeature 4",
    fill="#000000",
    font=("Young Serif", 18 * -1),
)
canvas.create_text(1007.0, 793.0, anchor="nw", text="-", fill="#000000", font=("Kodchasan Regular", 40 * -1))
canvas.create_text(976.0, 743.0, anchor="nw", text="Cluster 3", fill="#2E136B", font=("Young Serif", 18 * -1))

canvas.create_text(
    653.0,
    842.0,
    anchor="nw",
    text="Feature 1\nFeature 2\nFeature 3\nFeature 4",
    fill="#000000",
    font=("Young Serif", 18 * -1),
)
canvas.create_text(733.0, 780.0, anchor="nw", text="118", fill="#000000", font=("Kodchasan Regular", 40 * -1))
canvas.create_text(721.0, 743.0, anchor="nw", text="Cluster 2", fill="#2E136B", font=("Young Serif", 18 * -1))

canvas.create_text(
    396.0,
    842.0,
    anchor="nw",
    text="Feature 1\nFeature 2\nFeature 3\nFeature 4",
    fill="#000000",
    font=("Young Serif", 18 * -1),
)
canvas.create_text(462.0, 780.0, anchor="nw", text="244", fill="#000000", font=("Kodchasan Regular", 40 * -1))
canvas.create_text(465.0, 743.0, anchor="nw", text="Cluster 1", fill="#2E126A", font=("Kodchasan Bold", 18 * -1))

canvas.create_text(390.0, 122.0, anchor="nw", text="Scatter Plot Chart", fill="#000000", font=("Young Serif", 20 * -1))
canvas.create_text(1100.0, 467.0, anchor="nw", text="Elbow Method", fill="#000000", font=("Young Serif", 20 * -1))
canvas.create_text(
    1100.0,
    120.0,
    anchor="nw",
    text="Cluster Distribution Chart",
    fill="#000000",
    font=("Young Serif", 20 * -1),
)

canvas.create_text(
    100.0,
    927.0,
    anchor="nw",
    text="ChuLiBi",
    fill="#FDE5F4",
    font=("Rubik Burned Regular", 35 * -1),
)

# ===== Buttons (tên/toạ độ/ảnh theo file 2; giữ reference để không GC) =====
img_profile = PhotoImage(file=relative_to_assets("button_Profile.png"))
button_Profile = Button(image=img_profile, borderwidth=0, highlightthickness=0,
                        command=lambda: print("button_Profile clicked"), relief="flat")
button_Profile.image = img_profile
button_Profile.place(x=1376.0, y=25.0, width=44.0, height=45.0)

img_rec = PhotoImage(file=relative_to_assets("button_Recommendation.png"))
button_Recommendation = Button(image=img_rec, borderwidth=0, highlightthickness=0,
                               command=lambda: print("button_Recommendation clicked"), relief="flat")
button_Recommendation.image = img_rec
button_Recommendation.place(x=2.0, y=468.0, width=336.0, height=82.0)

img_churn = PhotoImage(file=relative_to_assets("button_Churn.png"))
button_Churn = Button(image=img_churn, borderwidth=0, highlightthickness=0,
                      command=lambda: print("button_Churn clicked"), relief="flat")
button_Churn.image = img_churn
button_Churn.place(x=2.0, y=381.0, width=336.0, height=86.0)

img_delivery = PhotoImage(file=relative_to_assets("button_Delivery.png"))
button_Delivery = Button(image=img_delivery, borderwidth=0, highlightthickness=0,
                         command=lambda: print("button_Delivery clicked"), relief="flat")
button_Delivery.image = img_delivery
button_Delivery.place(x=2.0, y=552.0, width=337.0, height=90.0)

img_report = PhotoImage(file=relative_to_assets("button_Report.png"))
button_Report = Button(image=img_report, borderwidth=0, highlightthickness=0,
                       command=lambda: print("button_Report clicked"), relief="flat")
button_Report.image = img_report
button_Report.place(x=2.0, y=646.0, width=337.0, height=87.0)

img_customer_analysis = PhotoImage(file=relative_to_assets("button_Customer_analysis.png"))
button_Customer_analysis = Button(image=img_customer_analysis, borderwidth=0, highlightthickness=0,
                                  command=lambda: print("button_Customer_analysis clicked"), relief="flat")
button_Customer_analysis.image = img_customer_analysis
button_Customer_analysis.place(x=19.0, y=304.0, width=320.0, height=76.0)

img_notification = PhotoImage(file=relative_to_assets("button_Notification.png"))
button_Notification = Button(image=img_notification, borderwidth=0, highlightthickness=0,
                             command=lambda: print("button_Notification clicked"), relief="flat")
button_Notification.image = img_notification
button_Notification.place(x=1309.0, y=27.0, width=44.0, height=42.0)

img_dashboard = PhotoImage(file=relative_to_assets("button_Dashboard.png"))
button_Dashboard = Button(image=img_dashboard, borderwidth=0, highlightthickness=0,
                          command=lambda: print("button_Dashboard clicked"), relief="flat")
button_Dashboard.image = img_dashboard
button_Dashboard.place(x=2.0, y=198.0, width=335.0, height=87.0)

# ===== Run =====
window.resizable(False, False)
window.mainloop()
