
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"assets_Frame07")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1440x1024")
window.configure(bg = "#D9D9D9")


canvas = Canvas(
    window,
    bg = "#D9D9D9",
    height = 1024,
    width = 1440,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    887.0,
    31.0,
    image=image_image_1
)

canvas.create_text(
    337.0,
    0.0,
    anchor="nw",
    text="   Customer Segmentation",
    fill="#000000",
    font=("Young Serif", 40 * -1)
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    1320.0,
    31.0,
    image=image_image_2
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    580.0,
    205.0,
    image=image_image_3
)

canvas.create_text(
    490.0,
    85.0,
    anchor="nw",
    text="Elbow Method",
    fill="#706093",
    font=("Young Serif", 24 * -1)
)
text_spaced = "   ".join("RESULT")
canvas.create_text(
    985.0,
    75.0,
    anchor="nw",
    text=text_spaced,
    fill="#706093",
    font=("Young Serif", 40 * -1)
)

canvas.create_rectangle(
    824.0,
    62.0,
    825.0,
    353.0,
    fill="#706093",
    outline="")

canvas.create_rectangle(
    332.0,
    352.0,
    825.0,
    353.00000000000006,
    fill="#706093",
    outline="")

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    1131.0,
    306.0,
    image=image_image_4
)

canvas.create_text(
    972.0,
    168.0,
    anchor="nw",
    text="Cluster Distribution Chart",
    fill="#706093",
    font=("Young Serif", 24 * -1)
)

image_image_5 = PhotoImage(
    file=relative_to_assets("image_5.png"))
image_5 = canvas.create_image(
    1130.0,
    735.0,
    image=image_image_5
)

canvas.create_text(
    1020.0,
    479.0,
    anchor="nw",
    text="Scatter Plot Chart",
    fill="#706093",
    font=("Young Serif", 24 * -1)
)

image_image_6 = PhotoImage(
    file=relative_to_assets("image_6.png"))
image_6 = canvas.create_image(
    588.0,
    688.0,
    image=image_image_6
)

canvas.create_text(
    472.0,
    390.0,
    anchor="nw",
    text="Characteristics of",
    fill="#706093",
    font=("Young Serif", 24 * -1)
)

canvas.create_text(
    443.0,
    424.0,
    anchor="nw",
    text="Customer Segmentation",
    fill="#706093",
    font=("Young Serif", 24 * -1)
)

canvas.create_text(
    609.0,
    516.0,
    anchor="nw",
    text="Feature 1",
    fill="#000000",
    font=("Crimson Pro", 18 * -1)
)

canvas.create_text(
    609.0,
    689.0,
    anchor="nw",
    text="Feature 1",
    fill="#000000",
    font=("Crimson Pro", 18 * -1)
)

canvas.create_text(
    609.0,
    860.0,
    anchor="nw",
    text="Feature 1",
    fill="#000000",
    font=("Crimson Pro", 18 * -1)
)

image_image_7 = PhotoImage(
    file=relative_to_assets("image_7.png"))
image_7 = canvas.create_image(
    588.0,
    551.0,
    image=image_image_7
)

image_image_8 = PhotoImage(
    file=relative_to_assets("image_8.png"))
image_8 = canvas.create_image(
    588.0,
    724.0,
    image=image_image_8
)

image_image_9 = PhotoImage(
    file=relative_to_assets("image_9.png"))
image_9 = canvas.create_image(
    588.0,
    896.0,
    image=image_image_9
)

canvas.create_text(
    421.0,
    548.0,
    anchor="nw",
    text="244",
    fill="#000000",
    font=("Kodchasan Regular", 40 * -1)
)

canvas.create_text(
    421.0,
    721.0,
    anchor="nw",
    text="244",
    fill="#000000",
    font=("Kodchasan Regular", 40 * -1)
)

canvas.create_text(
    421.0,
    895.0,
    anchor="nw",
    text="244",
    fill="#000000",
    font=("Kodchasan Regular", 40 * -1)
)

canvas.create_text(
    421.0,
    491.0,
    anchor="nw",
    text="Cluster 1",
    fill="#2E126A",
    font=("Young Serif", 20 * -1)
)

canvas.create_text(
    421.0,
    665.0,
    anchor="nw",
    text="Cluster 2",
    fill="#2E126A",
    font=("Young Serif", 20 * -1)
)

canvas.create_text(
    421.0,
    837.0,
    anchor="nw",
    text="Cluster 3",
    fill="#2E126A",
    font=("Young Serif", 20 * -1)
)

canvas.create_text(
    120.0,
    918.0,
    anchor="nw",
    text="ChuLiBi",
    fill="#FDE5F4",
    font=("Rubik Burned Regular", 35 * -1)
)

image_image_10 = PhotoImage(
    file=relative_to_assets("image_10.png"))
image_10 = canvas.create_image(
    168.0,
    512.0,
    image=image_image_10
)

canvas.create_text(
    98.0,
    927.0,
    anchor="nw",
    text="ChuLiBi",
    fill="#FDE5F4",
    font=("Rubik Burned Regular", 35 * -1)
)

image_image_11 = PhotoImage(
    file=relative_to_assets("image_11.png"))
image_11 = canvas.create_image(
    162.0,
    101.0,
    image=image_image_11
)

button_image_Recommendation = PhotoImage(
    file=relative_to_assets("button_Recommendation.png"))
button_Recommendation = Button(
    image=button_image_Recommendation,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_Recommendation clicked"),
    relief="flat"
)
button_Recommendation.place(
    x=0.0,
    y=468.0,
    width=336.0,
    height=82.0
)

button_image_Churn = PhotoImage(
    file=relative_to_assets("button_Churn.png"))
button_Churn = Button(
    image=button_image_Churn,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_Churn clicked"),
    relief="flat"
)
button_Churn.place(
    x=0.0,
    y=381.0,
    width=336.0,
    height=86.0
)

button_image_Delivery = PhotoImage(
    file=relative_to_assets("button_Delivery.png"))
button_Delivery = Button(
    image=button_image_Delivery,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_Delivery clicked"),
    relief="flat"
)
button_Delivery.place(
    x=0.0,
    y=552.0,
    width=337.0,
    height=90.0
)

button_image_Report = PhotoImage(
    file=relative_to_assets("button_Report.png"))
button_Report = Button(
    image=button_image_Report,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_Report clicked"),
    relief="flat"
)
button_Report.place(
    x=0.0,
    y=646.0,
    width=338.0,
    height=88.0
)

button_image_Dashboard = PhotoImage(
    file=relative_to_assets("button_Dashboard.png"))
button_Dashboard = Button(
    image=button_image_Dashboard,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_Dashboard clicked"),
    relief="flat"
)
button_Dashboard.place(
    x=0.0,
    y=193.0,
    width=336.0,
    height=88.0
)

button_image_Profile = PhotoImage(
    file=relative_to_assets("button_Profile.png"))
button_Profile = Button(
    image=button_image_Profile,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_Profile clicked"),
    relief="flat"
)
button_Profile.place(
    x=1359.0,
    y=7.0,
    width=53.0,
    height=48.0
)

button_image_CustomerAnalysis = PhotoImage(
    file=relative_to_assets("button_CustomerAnalysis.png"))
button_CustomerAnalysis = Button(
    image=button_image_CustomerAnalysis,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_CustomerAnalysis clicked"),
    relief="flat"
)
button_CustomerAnalysis.place(
    x=0.0,
    y=273.0,
    width=336.0,
    height=100.0
)


window.resizable(False, False)
window.mainloop()
